name: Build and Push Docker Dev Images

on:
  push:
    branches:
      - main # Change to the appropriate branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Checkout Repos
      run: ./get_repos.sh

    - name: Build and Push Docker Images
      run: |
        docker-compose -f docker-compose-dev.yml build
        docker-compose push valis
        docker-compose push zora

    - name: Cleanup
      run: |
        docker-compose down --rmi local
        docker logout ghcr.io
