name: Build and Push Docker Dev Images

on:
  push:
    branches:
      - main # Change to the appropriate branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set docker tags
      id: set-tags
      run: |
        if [[ $GITHUB_REF == refs/heads/main ]]
        then
          echo TAGS=$USER/$APP:latest >> $GITHUB_OUTPUT
        elif [[ $GITHUB_REF == refs/heads/* ]]
        then
          BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's/[\/]/_/g')
          echo TAGS=$USER/$APP:$BRANCH >> $GITHUB_OUTPUT
        else
          echo TAGS=$USER/$APP:${GITHUB_REF#refs/tags/} >> $GITHUB_OUTPUT
        fi

    - name: Show tags
      run: echo ${{ steps.set-tags.outputs.TAGS }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Checkout Repos
      run: ./get_repos.sh

    - name: Build and Push Docker Images
      run: |
        docker-compose -f docker-compose-dev.yml build
        docker-compose push ghcr.io/sdss/valis/valis-dev:latest
        docker-compose push ghcr.io/sdss/zora/zora-dev:latest

    - name: Cleanup
      run: |
        docker-compose down --rmi local
        docker logout ghcr.io
